#This is the default localization file.

#The solution's localized name displayed in UI
DISPLAY_NAME=capacityPublix

#The solution's localized description
DESCRIPTION=capacity adapter in support of Publix

#The vendor's localized name
VENDOR=Broadcom
