#This is the default localization file.

#The solution's localized name displayed in UI
DISPLAY_NAME=Cluster Performance Risk

#The solution's localized description
DESCRIPTION=Self-referential adapter that scores VMware Cloud Foundation cluster performance risk from native vSphere/DRS metrics.

#The vendor's localized name
VENDOR=gillaspy
